### ISSUE TITLE
what format of labels_combined_complete.csv is

### ISSUE THREAD

**Issue by njtuzzy** [wAuner/traffic_detection_yolo2#1]
can you gave an example of format of labels_combined_complete.csv in your code?

**Comment by zhyj3038** [comment]
hello , I am also confused with the data format, especially "labels" and  "mask_vals" in get_batches func,  can you give an example?  thanks very much for your beautiful code!

**Comment by zzsd** [comment]
hello, could you share an example  in "labels_combined_complete.csv".I want to know about more detail about how processing data. Thank you for your code.
